import type { ScanResult } from "@/lib/detector/types";
import {
  SEVERITY_LABEL,
  CATEGORY_LABEL,
  VERDICT_META,
} from "@/lib/severity";

/**
 * Render a ScanResult as a self-contained Markdown report.
 * Suitable for sharing in PRs, tickets, or pasting into docs.
 */
export function scanResultToMarkdown(result: ScanResult): string {
  const lines: string[] = [];
  const v = VERDICT_META[result.verdict];
  const date = new Date(result.scannedAt).toISOString();

  lines.push(`# BackdoorSniper Scan Report`);
  lines.push("");
  lines.push(`- **Verdict:** ${v.label}`);
  lines.push(`- **Risk Score:** ${result.riskScore} / 100`);
  lines.push(`- **Total Findings:** ${result.stats.totalFindings}`);
  lines.push(`- **Lines Scanned:** ${result.stats.totalLines}`);
  lines.push(`- **Scan Duration:** ${result.durationMs} ms`);
  lines.push(`- **Source Hash:** \`${result.sourceHash}\``);
  lines.push(`- **Scanned At:** ${date}`);
  lines.push("");

  // Severity breakdown
  lines.push(`## Severity Breakdown`);
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  (["critical", "high", "medium", "low", "info"] as const).forEach((sev) => {
    lines.push(
      `| ${SEVERITY_LABEL[sev]} | ${result.stats.bySeverity[sev]} |`
    );
  });
  lines.push("");

  // Category breakdown
  const cats = Object.entries(result.stats.byCategory).filter(([, n]) => n > 0);
  if (cats.length > 0) {
    lines.push(`## Categories Triggered`);
    lines.push("");
    lines.push("| Category | Count |");
    lines.push("|----------|-------|");
    cats
      .sort((a, b) => b[1] - a[1])
      .forEach(([cat, n]) => {
        const label =
          CATEGORY_LABEL[cat as keyof typeof CATEGORY_LABEL] ?? cat;
        lines.push(`| ${label} | ${n} |`);
      });
    lines.push("");
  }

  // Findings
  if (result.findings.length === 0) {
    lines.push(`## Findings`);
    lines.push("");
    lines.push("_No backdoor patterns detected._");
    lines.push("");
  } else {
    lines.push(`## Findings`);
    lines.push("");
    result.findings.forEach((f, i) => {
      const sev = SEVERITY_LABEL[f.severity];
      const cat =
        CATEGORY_LABEL[f.category as keyof typeof CATEGORY_LABEL] ?? f.category;
      lines.push(`### ${i + 1}. [${sev}] ${f.title}`);
      lines.push("");
      lines.push(`- **Rule ID:** \`${f.ruleId}\``);
      lines.push(`- **Line:** ${f.line}`);
      lines.push(`- **Category:** ${cat}`);
      lines.push(`- **Confidence:** ${Math.round(f.confidence * 100)}%`);
      if (f.references && f.references.length > 0) {
        lines.push(`- **References:** ${f.references.join(", ")}`);
      }
      lines.push("");
      lines.push(`**Source snippet:**`);
      lines.push("");
      lines.push("```python");
      lines.push(f.snippet || "(empty line)");
      lines.push("```");
      lines.push("");
      lines.push(`**Why this is dangerous:**`);
      lines.push("");
      lines.push(f.description);
      lines.push("");
      lines.push(`**How to fix:**`);
      lines.push("");
      lines.push(f.remediation);
      lines.push("");
      lines.push("---");
      lines.push("");
    });
  }

  lines.push("");
  lines.push(`---`);
  lines.push(`_Generated by [BackdoorSniper](https://example.com) — static Python backdoor analysis._`);

  return lines.join("\n");
}

/**
 * Render a ScanResult as a compact, Slack/Teams-friendly text summary.
 * Designed for quick sharing in chat or as a PR comment.
 */
export function scanResultToCompactSummary(result: ScanResult): string {
  const v = VERDICT_META[result.verdict];
  const lines: string[] = [];

  lines.push(`🔒 BackdoorSniper Scan Result`);
  lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(``);

  // Verdict + risk with visual bar
  const barLen = 20;
  const filled = Math.round((result.riskScore / 100) * barLen);
  const bar = "█".repeat(filled) + "░".repeat(barLen - filled);
  lines.push(`Verdict:  ${v.label}`);
  lines.push(`Risk:     ${bar} ${result.riskScore}/100`);
  lines.push(`Findings: ${result.stats.totalFindings} · Lines: ${result.stats.totalLines}`);
  lines.push(``);

  // Severity counts
  const sevParts: string[] = [];
  (["critical", "high", "medium", "low", "info"] as const).forEach((sev) => {
    const n = result.stats.bySeverity[sev];
    if (n > 0) sevParts.push(`${SEVERITY_LABEL[sev]}: ${n}`);
  });
  if (sevParts.length > 0) {
    lines.push(`Severity: ${sevParts.join(" · ")}`);
  }

  // Top categories
  const cats = Object.entries(result.stats.byCategory)
    .filter(([, n]) => n > 0)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);
  if (cats.length > 0) {
    const catParts = cats.map(([cat, n]) => {
      const label = CATEGORY_LABEL[cat as keyof typeof CATEGORY_LABEL] ?? cat;
      return `${label}(${n})`;
    });
    lines.push(`Categories: ${catParts.join(" · ")}`);
  }

  lines.push(``);

  // Top findings (up to 5)
  if (result.findings.length > 0) {
    lines.push(`Top Findings:`);
    result.findings.slice(0, 5).forEach((f) => {
      const sev = SEVERITY_LABEL[f.severity].toUpperCase().slice(0, 4);
      lines.push(`  [${sev}] L${f.line} ${f.ruleId} — ${f.title}`);
    });
    if (result.findings.length > 5) {
      lines.push(`  … and ${result.findings.length - 5} more`);
    }
  } else {
    lines.push(`✅ No backdoor patterns detected.`);
  }

  lines.push(``);
  lines.push(`Hash: ${result.sourceHash} · ${new Date(result.scannedAt).toISOString()}`);
  lines.push(`— BackdoorSniper`);

  return lines.join("\n");
}
