#!/usr/bin/env python3
"""
BackdoorSniper PDF Report Generator

Takes a JSON ScanResult via stdin, generates a professional dark-themed PDF
report using ReportLab, saves it, and prints the output path to stdout.

Usage:
    echo '<json>' | python3 generate-pdf-report.py
"""

import sys
import json
import os
import tempfile
import hashlib
import re
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━

PAGE_BG       = colors.HexColor('#131311')
SECTION_BG    = colors.HexColor('#23221f')
CARD_BG       = colors.HexColor('#211f1b')
TABLE_STRIPE  = colors.HexColor('#1e1d19')
HEADER_FILL   = colors.HexColor('#4b4430')
COVER_BLOCK   = colors.HexColor('#413b28')
BORDER        = colors.HexColor('#514c3b')
ICON          = colors.HexColor('#d0c08f')
ACCENT        = colors.HexColor('#ceaf51')
ACCENT_2      = colors.HexColor('#5fa9c2')
TEXT_PRIMARY   = colors.HexColor('#e5e4e2')
TEXT_MUTED     = colors.HexColor('#93908a')

SEM_SUCCESS   = colors.HexColor('#7ec295')
SEM_WARNING   = colors.HexColor('#c6b084')
SEM_ERROR     = colors.HexColor('#bd746d')
SEM_INFO      = colors.HexColor('#6a94be')

# Severity colors (emerald accent system, no indigo/blue)
SEV_CRITICAL = colors.HexColor('#ef4444')
SEV_HIGH     = colors.HexColor('#f97316')
SEV_MEDIUM   = colors.HexColor('#f59e0b')
SEV_LOW      = colors.HexColor('#10b981')
SEV_INFO     = colors.HexColor('#94a3b8')

SEV_COLORS = {
    'critical': SEV_CRITICAL,
    'high': SEV_HIGH,
    'medium': SEV_MEDIUM,
    'low': SEV_LOW,
    'info': SEV_INFO,
}

SEV_LABELS = {
    'critical': 'Critical',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'info': 'Info',
}

CATEGORY_LABELS = {
    'code-execution': 'Code Execution',
    'command-execution': 'Command Execution',
    'network': 'Network',
    'reverse-shell': 'Reverse Shell',
    'obfuscation': 'Obfuscation',
    'deserialization': 'Deserialization',
    'dangerous-import': 'Dangerous Import',
    'persistence': 'Persistence',
    'credential-theft': 'Credential Theft',
    'privilege-escalation': 'Privilege Escalation',
    'exfiltration': 'Exfiltration',
    'anti-analysis': 'Anti-Analysis',
    'filesystem': 'Filesystem',
    'hardcoded-secret': 'Hardcoded Secret',
    'suspicious-pattern': 'Suspicious Pattern',
}

VERDICT_LABELS = {
    'clean': 'Clean',
    'suspicious': 'Suspicious',
    'malicious': 'Malicious',
    'dangerous': 'Dangerous',
}

VERDICT_COLORS = {
    'clean': SEM_SUCCESS,
    'suspicious': SEM_WARNING,
    'malicious': SEM_ERROR,
    'dangerous': SEV_CRITICAL,
}

# ━━ Font Registration ━━

import platform
_IS_MAC = platform.system() == 'Darwin'
if _IS_MAC:
    FONT_DIR = os.path.expanduser('~/.openclaw/workspace/fonts')
else:
    FONT_DIR = '/usr/share/fonts'

pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))

registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                    italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')

# Note: install_font_fallback is skipped for performance.
# This report is English-only and doesn't need CJK fallback.

# ━━ Content Sanitization ━━

def content_sanitize(text):
    """Strip invisible/control chars from text."""
    text = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]', '', text)
    text = re.sub(r'[\u200b-\u200f\u2028-\u202f\u2060\ufeff]', '', text)
    text = text.replace('\ufffd', '')
    text = re.sub(r'[\ufe00-\ufe0f]', '', text)
    text = re.sub(r'[\ue000-\uf8ff]', '', text)
    return text

def escape_xml(text):
    """Escape XML special characters for ReportLab Paragraph."""
    text = text.replace('&', '&amp;')
    text = text.replace('<', '&lt;')
    text = text.replace('>', '&gt;')
    text = text.replace('"', '&quot;')
    return text

# ━━ Styles ━━

PAGE_W, PAGE_H = A4
MARGIN = 20 * mm

style_title = ParagraphStyle(
    name='ReportTitle',
    fontName='FreeSerif-Bold',
    fontSize=22,
    leading=28,
    textColor=ACCENT,
    alignment=TA_CENTER,
    spaceAfter=4,
)

style_subtitle = ParagraphStyle(
    name='ReportSubtitle',
    fontName='FreeSerif-Italic',
    fontSize=10,
    leading=14,
    textColor=TEXT_MUTED,
    alignment=TA_CENTER,
    spaceAfter=6,
)

style_h1 = ParagraphStyle(
    name='H1',
    fontName='FreeSerif-Bold',
    fontSize=16,
    leading=22,
    textColor=ACCENT,
    spaceAfter=6,
    spaceBefore=14,
)

style_h2 = ParagraphStyle(
    name='H2',
    fontName='FreeSerif-Bold',
    fontSize=13,
    leading=18,
    textColor=TEXT_PRIMARY,
    spaceAfter=4,
    spaceBefore=10,
)

style_body = ParagraphStyle(
    name='Body',
    fontName='FreeSerif',
    fontSize=9.5,
    leading=15,
    textColor=TEXT_PRIMARY,
    alignment=TA_LEFT,
)

style_body_muted = ParagraphStyle(
    name='BodyMuted',
    fontName='FreeSerif-Italic',
    fontSize=8.5,
    leading=13,
    textColor=TEXT_MUTED,
)

style_code = ParagraphStyle(
    name='Code',
    fontName='DejaVuSans',
    fontSize=8,
    leading=12,
    textColor=ACCENT,
    leftIndent=8,
)

style_table_header = ParagraphStyle(
    name='TableHeader',
    fontName='FreeSerif-Bold',
    fontSize=9,
    leading=13,
    textColor=colors.white,
    alignment=TA_CENTER,
)

style_table_cell = ParagraphStyle(
    name='TableCell',
    fontName='FreeSerif',
    fontSize=9,
    leading=13,
    textColor=TEXT_PRIMARY,
    alignment=TA_CENTER,
)

style_table_cell_left = ParagraphStyle(
    name='TableCellLeft',
    fontName='FreeSerif',
    fontSize=9,
    leading=13,
    textColor=TEXT_PRIMARY,
    alignment=TA_LEFT,
)

style_badge = ParagraphStyle(
    name='Badge',
    fontName='FreeSerif-Bold',
    fontSize=8,
    leading=11,
    alignment=TA_CENTER,
)

style_footer = ParagraphStyle(
    name='Footer',
    fontName='FreeSerif-Italic',
    fontSize=7,
    leading=10,
    textColor=TEXT_MUTED,
    alignment=TA_CENTER,
)

style_finding_title = ParagraphStyle(
    name='FindingTitle',
    fontName='FreeSerif-Bold',
    fontSize=10,
    leading=14,
    textColor=TEXT_PRIMARY,
    spaceAfter=2,
)

style_finding_detail = ParagraphStyle(
    name='FindingDetail',
    fontName='FreeSerif',
    fontSize=9,
    leading=14,
    textColor=TEXT_PRIMARY,
    leftIndent=6,
)

style_finding_label = ParagraphStyle(
    name='FindingLabel',
    fontName='FreeSerif-Bold',
    fontSize=8.5,
    leading=12,
    textColor=ACCENT,
    leftIndent=6,
)

# ━━ Page Template ━━

def draw_page_bg(canvas, doc):
    """Draw dark background and footer on every page."""
    canvas.saveState()
    # Full page dark background
    canvas.setFillColor(PAGE_BG)
    canvas.rect(0, 0, PAGE_W, PAGE_H, fill=True, stroke=False)
    # Top accent line
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.5)
    canvas.line(MARGIN, PAGE_H - 14*mm, PAGE_W - MARGIN, PAGE_H - 14*mm)
    # Footer
    canvas.setFont('FreeSerif-Italic', 7)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawCentredString(PAGE_W / 2, 12*mm,
        f'BackdoorSniper Security Report  |  Page {doc.page}')
    # Bottom accent line
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 18*mm, PAGE_W - MARGIN, 18*mm)
    canvas.restoreState()


def draw_cover_bg(canvas, doc):
    """Draw cover page background."""
    canvas.saveState()
    # Full page dark background
    canvas.setFillColor(PAGE_BG)
    canvas.rect(0, 0, PAGE_W, PAGE_H, fill=True, stroke=False)
    # Top accent block
    canvas.setFillColor(COVER_BLOCK)
    canvas.rect(0, PAGE_H - 80*mm, PAGE_W, 80*mm, fill=True, stroke=False)
    # Accent line
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(3)
    canvas.line(MARGIN, PAGE_H - 80*mm, PAGE_W - MARGIN, PAGE_H - 80*mm)
    # Bottom accent line
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1)
    canvas.line(MARGIN, 40*mm, PAGE_W - MARGIN, 40*mm)
    canvas.restoreState()


# ━━ Builder ━━

def build_report(scan_result):
    """Build the PDF report from a ScanResult dict."""
    source_hash = scan_result.get('sourceHash', 'unknown')
    output_dir = tempfile.gettempdir()
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, f'backdoorsniper-report-{source_hash}.pdf')

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=20*mm,
        bottomMargin=24*mm,
    )

    usable_w = PAGE_W - 2 * MARGIN
    story = []

    # ── Cover Page ──
    story.append(Spacer(1, 30*mm))
    story.append(Paragraph(
        '<font color="#ceaf51">BackdoorSniper</font>',
        ParagraphStyle(name='CoverBrand', fontName='FreeSerif-Bold', fontSize=14,
                       leading=18, textColor=ACCENT, alignment=TA_CENTER)
    ))
    story.append(Spacer(1, 8*mm))
    story.append(Paragraph(
        'Security Scan Report',
        ParagraphStyle(name='CoverTitle', fontName='FreeSerif-Bold', fontSize=30,
                       leading=36, textColor=TEXT_PRIMARY, alignment=TA_CENTER)
    ))
    story.append(Spacer(1, 6*mm))

    verdict = scan_result.get('verdict', 'clean')
    verdict_label = VERDICT_LABELS.get(verdict, verdict.upper())
    verdict_color = VERDICT_COLORS.get(verdict, TEXT_MUTED)
    vc_hex = '#%02x%02x%02x' % (int(verdict_color.red*255), int(verdict_color.green*255), int(verdict_color.blue*255))

    risk_score = scan_result.get('riskScore', 0)
    total_findings = scan_result.get('stats', {}).get('totalFindings', 0)
    total_lines = scan_result.get('stats', {}).get('totalLines', 0)
    duration_ms = scan_result.get('durationMs', 0)
    scanned_at = scan_result.get('scannedAt', '')
    try:
        dt = datetime.fromisoformat(scanned_at.replace('Z', '+00:00'))
        date_str = dt.strftime('%Y-%m-%d %H:%M:%S UTC')
    except Exception:
        date_str = scanned_at

    # Verdict badge
    story.append(Paragraph(
        f'<font color="{vc_hex}"><b>VERDICT: {verdict_label.upper()}</b></font>',
        ParagraphStyle(name='CoverVerdict', fontName='FreeSerif-Bold', fontSize=18,
                       leading=24, textColor=verdict_color, alignment=TA_CENTER)
    ))
    story.append(Spacer(1, 6*mm))

    # Key metrics on cover
    metrics_data = [
        [Paragraph('<b>Risk Score</b>', style_table_header),
         Paragraph('<b>Findings</b>', style_table_header),
         Paragraph('<b>Lines</b>', style_table_header),
         Paragraph('<b>Duration</b>', style_table_header)],
        [Paragraph(f'<font color="{vc_hex}"><b>{risk_score}</b></font><font color="#93908a">/100</font>', style_table_cell),
         Paragraph(str(total_findings), style_table_cell),
         Paragraph(str(total_lines), style_table_cell),
         Paragraph(f'{duration_ms}ms', style_table_cell)],
    ]
    metrics_table = Table(metrics_data, colWidths=[usable_w/4]*4)
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('BACKGROUND', (0, 1), (-1, 1), CARD_BG),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(metrics_table)

    story.append(Spacer(1, 10*mm))
    story.append(Paragraph(
        f'Source Hash: <font name="DejaVuSans" size="8">{escape_xml(source_hash)}</font>',
        ParagraphStyle(name='CoverHash', fontName='FreeSerif', fontSize=9,
                       leading=13, textColor=TEXT_MUTED, alignment=TA_CENTER)
    ))
    story.append(Spacer(1, 3*mm))
    story.append(Paragraph(
        f'Scanned: {escape_xml(date_str)}',
        ParagraphStyle(name='CoverDate', fontName='FreeSerif', fontSize=9,
                       leading=13, textColor=TEXT_MUTED, alignment=TA_CENTER)
    ))
    story.append(Spacer(1, 10*mm))
    story.append(Paragraph(
        'Generated by BackdoorSniper - Static Python Backdoor Analysis',
        ParagraphStyle(name='CoverFooter', fontName='FreeSerif-Italic', fontSize=8,
                       leading=11, textColor=TEXT_MUTED, alignment=TA_CENTER)
    ))

    story.append(PageBreak())

    # ── Summary Section ──
    story.append(Paragraph('Executive Summary', style_h1))
    story.append(HRFlowable(width='100%', thickness=1, color=ACCENT, spaceAfter=8))

    summary_items = [
        ('Verdict', f'<font color="{vc_hex}"><b>{verdict_label}</b></font>'),
        ('Risk Score', f'<font color="{vc_hex}"><b>{risk_score}</b></font> out of 100'),
        ('Total Findings', str(total_findings)),
        ('Lines Scanned', str(total_lines)),
        ('Source Hash', f'<font name="DejaVuSans" size="8">{escape_xml(source_hash)}</font>'),
        ('Scan Duration', f'{duration_ms} ms'),
        ('Scanned At', escape_xml(date_str)),
    ]

    summary_data = []
    for label, value in summary_items:
        summary_data.append([
            Paragraph(f'<b>{label}</b>', ParagraphStyle(
                name=f'SumLabel_{label}', fontName='FreeSerif-Bold', fontSize=9.5,
                leading=14, textColor=ACCENT)),
            Paragraph(value, ParagraphStyle(
                name=f'SumVal_{label}', fontName='FreeSerif', fontSize=9.5,
                leading=14, textColor=TEXT_PRIMARY)),
        ])

    summary_table = Table(summary_data, colWidths=[usable_w * 0.3, usable_w * 0.7])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), SECTION_BG),
        ('BACKGROUND', (1, 0), (1, -1), CARD_BG),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 12))

    # ── Severity Breakdown ──
    story.append(Paragraph('Severity Breakdown', style_h1))
    story.append(HRFlowable(width='100%', thickness=1, color=ACCENT, spaceAfter=8))

    by_severity = scan_result.get('stats', {}).get('bySeverity', {})
    sev_data = [
        [Paragraph('<b>Severity</b>', style_table_header),
         Paragraph('<b>Count</b>', style_table_header),
         Paragraph('<b>Bar</b>', style_table_header)],
    ]

    max_count = max((by_severity.get(s, 0) for s in ['critical','high','medium','low','info']), default=1) or 1
    for sev in ['critical', 'high', 'medium', 'low', 'info']:
        count = by_severity.get(sev, 0)
        sev_color = SEV_COLORS.get(sev, TEXT_MUTED)
        sc_hex = '#%02x%02x%02x' % (int(sev_color.red*255), int(sev_color.green*255), int(sev_color.blue*255))
        bar_width = int((count / max_count) * 200) if max_count > 0 else 0
        bar_html = ''
        if count > 0:
            bar_html = f'<font color="{sc_hex}">' + '&#9608;' * max(bar_width // 8, 1) + '</font>'
        sev_data.append([
            Paragraph(f'<font color="{sc_hex}"><b>{SEV_LABELS[sev]}</b></font>',
                      style_table_cell_left),
            Paragraph(str(count), style_table_cell),
            Paragraph(bar_html, style_table_cell_left),
        ])

    sev_table = Table(sev_data, colWidths=[usable_w * 0.25, usable_w * 0.15, usable_w * 0.60])
    sev_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('BACKGROUND', (0, 1), (-1, -1), CARD_BG),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [CARD_BG, TABLE_STRIPE]),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(sev_table)
    story.append(Spacer(1, 12))

    # ── Category Breakdown ──
    by_category = scan_result.get('stats', {}).get('byCategory', {})
    cats_with_findings = [(cat, count) for cat, count in by_category.items() if count > 0]
    cats_with_findings.sort(key=lambda x: x[1], reverse=True)

    if cats_with_findings:
        story.append(Paragraph('Category Breakdown', style_h1))
        story.append(HRFlowable(width='100%', thickness=1, color=ACCENT, spaceAfter=8))

        cat_data = [
            [Paragraph('<b>Category</b>', style_table_header),
             Paragraph('<b>Count</b>', style_table_header)],
        ]
        for cat, count in cats_with_findings:
            cat_label = CATEGORY_LABELS.get(cat, cat)
            cat_data.append([
                Paragraph(escape_xml(content_sanitize(cat_label)), style_table_cell_left),
                Paragraph(str(count), style_table_cell),
            ])

        cat_table = Table(cat_data, colWidths=[usable_w * 0.75, usable_w * 0.25])
        cat_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [CARD_BG, TABLE_STRIPE]),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(cat_table)
        story.append(Spacer(1, 12))

    # ── Findings Detail ──
    findings = scan_result.get('findings', [])
    if findings:
        story.append(Paragraph('Findings Detail', style_h1))
        story.append(HRFlowable(width='100%', thickness=1, color=ACCENT, spaceAfter=8))
        story.append(Spacer(1, 6))

        for i, f in enumerate(findings):
            sev = f.get('severity', 'info')
            sev_color = SEV_COLORS.get(sev, TEXT_MUTED)
            sc_hex = '#%02x%02x%02x' % (int(sev_color.red*255), int(sev_color.green*255), int(sev_color.blue*255))
            sev_label = SEV_LABELS.get(sev, sev.upper())
            rule_id = escape_xml(content_sanitize(f.get('ruleId', '')))
            title = escape_xml(content_sanitize(f.get('title', '')))
            line_num = f.get('line', 0)
            snippet = escape_xml(content_sanitize(f.get('snippet', '')))
            description = escape_xml(content_sanitize(f.get('description', '')))
            remediation = escape_xml(content_sanitize(f.get('remediation', '')))
            confidence = f.get('confidence', 0)
            confidence_pct = int(confidence * 100)
            category = f.get('category', '')
            cat_label = CATEGORY_LABELS.get(category, category)
            references = f.get('references', [])

            # Finding card as a nested table
            finding_elements = []

            # Header row: severity badge + rule id + title
            finding_elements.append(
                Paragraph(
                    f'<font color="{sc_hex}"><b>[{sev_label}]</b></font>  '
                    f'<font name="DejaVuSans" size="8">{rule_id}</font>  '
                    f'<b>{title}</b>',
                    style_finding_title
                )
            )

            # Meta info
            meta_parts = [
                f'Line: <b>{line_num}</b>',
                f'Category: {escape_xml(cat_label)}',
                f'Confidence: <b>{confidence_pct}%</b>',
            ]
            finding_elements.append(
                Paragraph('  |  '.join(meta_parts), style_body_muted)
            )

            # Snippet
            if snippet:
                # Truncate very long snippets
                display_snippet = snippet[:120] + '...' if len(snippet) > 120 else snippet
                finding_elements.append(Spacer(1, 4))
                finding_elements.append(
                    Paragraph(
                        f'<font name="DejaVuSans" size="7.5" color="#ceaf51">'
                        f'{display_snippet}</font>',
                        ParagraphStyle(name=f'Snippet_{i}', fontName='DejaVuSans',
                                       fontSize=7.5, leading=11, textColor=ACCENT,
                                       leftIndent=8, backColor=SECTION_BG)
                    )
                )

            # Why dangerous
            if description:
                finding_elements.append(Spacer(1, 4))
                finding_elements.append(
                    Paragraph(f'<b>Why dangerous:</b> {description}', style_finding_detail)
                )

            # How to fix
            if remediation:
                finding_elements.append(Spacer(1, 2))
                finding_elements.append(
                    Paragraph(f'<b>How to fix:</b> {remediation}', style_finding_detail)
                )

            # References
            if references:
                ref_str = ', '.join(escape_xml(r) for r in references)
                finding_elements.append(Spacer(1, 2))
                finding_elements.append(
                    Paragraph(f'<b>References:</b> {ref_str}', style_finding_detail)
                )

            # Wrap in a table card with colored left border
            inner_content = []
            for el in finding_elements:
                inner_content.append([el])

            inner_table = Table(inner_content, colWidths=[usable_w - 14])
            inner_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
                ('TOPPADDING', (0, 0), (-1, -1), 2),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ]))

            # Outer table with severity-colored left border
            border_cell = Paragraph('', ParagraphStyle(name=f'Border_{i}', fontSize=1))
            outer_data = [[border_cell, inner_table]]
            outer_table = Table(outer_data, colWidths=[4, usable_w - 4])
            outer_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), sev_color),
                ('BACKGROUND', (1, 0), (1, -1), CARD_BG),
                ('TOPPADDING', (0, 0), (-1, -1), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
                ('LEFTPADDING', (0, 0), (-1, -1), 0),
                ('RIGHTPADDING', (0, 0), (-1, -1), 0),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('BOX', (0, 0), (-1, -1), 0.5, BORDER),
            ]))

            story.append(outer_table)
            story.append(Spacer(1, 8))
    else:
        story.append(Paragraph('Findings', style_h1))
        story.append(HRFlowable(width='100%', thickness=1, color=ACCENT, spaceAfter=8))
        story.append(Paragraph(
            'No backdoor patterns detected. The scanned code appears clean.',
            style_body
        ))

    # ── Footer ──
    story.append(Spacer(1, 18))
    story.append(HRFlowable(width='100%', thickness=0.5, color=BORDER, spaceAfter=8))
    story.append(Paragraph(
        'Generated by <b>BackdoorSniper</b> - Static Python Backdoor Analysis  |  '
        f'{escape_xml(date_str)}',
        style_footer
    ))

    # Build with page backgrounds
    doc.build(story, onFirstPage=draw_cover_bg, onLaterPages=draw_page_bg)
    return output_path


def main():
    if len(sys.argv) < 2:
        print(json.dumps({'error': 'Usage: generate-pdf-report.py <input.json>'}), file=sys.stderr)
        sys.exit(1)

    input_file = sys.argv[1]
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            raw = f.read()
        if not raw.strip():
            print(json.dumps({'error': 'No input provided'}), file=sys.stderr)
            sys.exit(1)
        scan_result = json.loads(raw)
    except json.JSONDecodeError as e:
        print(json.dumps({'error': f'Invalid JSON: {str(e)}'}), file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError:
        print(json.dumps({'error': f'Input file not found: {input_file}'}), file=sys.stderr)
        sys.exit(1)

    try:
        output_path = build_report(scan_result)
        # Output result as JSON to stdout
        result = {
            'success': True,
            'path': output_path,
            'filename': os.path.basename(output_path),
        }
        print(json.dumps(result))
    except Exception as e:
        print(json.dumps({'error': f'PDF generation failed: {str(e)}'}), file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
